
--dataset sst2
--model-type bert-base
--batch-size 512
--logfile stage1_rl.log

--mode stage1-only
--skip-final-eval

--stage1-search-episodes 51000
--stage1-search-lr 2e-5
--ppo-update-interval 120
--random-seed 42

--stage1-accuracy-tolerance 0.0
